// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `PlateAcquisitionAnnotationLink.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __omero_model__opt_hudson_workspace_OMERO_5_0_release_src_components_blitz_generated_omero_model_PlateAcquisitionAnnotationLink_h__
#define __omero_model__opt_hudson_workspace_OMERO_5_0_release_src_components_blitz_generated_omero_model_PlateAcquisitionAnnotationLink_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <omero/model/IObject.h>
#include <omero/RTypes.h>
#include <omero/System.h>
#include <omero/Collections.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace omero
{

namespace model
{

class PlateAcquisition;

class Annotation;

class Details;

class PlateAcquisitionAnnotationLink;

}

}

}

namespace omero
{

namespace model
{

class PlateAcquisition;
bool operator==(const PlateAcquisition&, const PlateAcquisition&);
bool operator<(const PlateAcquisition&, const PlateAcquisition&);

class Annotation;
bool operator==(const Annotation&, const Annotation&);
bool operator<(const Annotation&, const Annotation&);

class Details;
bool operator==(const Details&, const Details&);
bool operator<(const Details&, const Details&);

class PlateAcquisitionAnnotationLink;
bool operator==(const PlateAcquisitionAnnotationLink&, const PlateAcquisitionAnnotationLink&);
bool operator<(const PlateAcquisitionAnnotationLink&, const PlateAcquisitionAnnotationLink&);

}

}

namespace IceInternal
{

::Ice::Object* upCast(::omero::model::PlateAcquisition*);
::IceProxy::Ice::Object* upCast(::IceProxy::omero::model::PlateAcquisition*);

::Ice::Object* upCast(::omero::model::Annotation*);
::IceProxy::Ice::Object* upCast(::IceProxy::omero::model::Annotation*);

::Ice::Object* upCast(::omero::model::Details*);
::IceProxy::Ice::Object* upCast(::IceProxy::omero::model::Details*);

::Ice::Object* upCast(::omero::model::PlateAcquisitionAnnotationLink*);
::IceProxy::Ice::Object* upCast(::IceProxy::omero::model::PlateAcquisitionAnnotationLink*);

}

namespace omero
{

namespace model
{

typedef ::IceInternal::Handle< ::omero::model::PlateAcquisition> PlateAcquisitionPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::omero::model::PlateAcquisition> PlateAcquisitionPrx;

void __read(::IceInternal::BasicStream*, PlateAcquisitionPrx&);
void __patch__PlateAcquisitionPtr(void*, ::Ice::ObjectPtr&);

typedef ::IceInternal::Handle< ::omero::model::Annotation> AnnotationPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::omero::model::Annotation> AnnotationPrx;

void __read(::IceInternal::BasicStream*, AnnotationPrx&);
void __patch__AnnotationPtr(void*, ::Ice::ObjectPtr&);

typedef ::IceInternal::Handle< ::omero::model::Details> DetailsPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::omero::model::Details> DetailsPrx;

void __read(::IceInternal::BasicStream*, DetailsPrx&);
void __patch__DetailsPtr(void*, ::Ice::ObjectPtr&);

typedef ::IceInternal::Handle< ::omero::model::PlateAcquisitionAnnotationLink> PlateAcquisitionAnnotationLinkPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::omero::model::PlateAcquisitionAnnotationLink> PlateAcquisitionAnnotationLinkPrx;

void __read(::IceInternal::BasicStream*, PlateAcquisitionAnnotationLinkPrx&);
void __patch__PlateAcquisitionAnnotationLinkPtr(void*, ::Ice::ObjectPtr&);

}

}

namespace omero
{

namespace model
{

class Callback_PlateAcquisitionAnnotationLink_getVersion_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_PlateAcquisitionAnnotationLink_getVersion_Base> Callback_PlateAcquisitionAnnotationLink_getVersionPtr;

class Callback_PlateAcquisitionAnnotationLink_setVersion_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_PlateAcquisitionAnnotationLink_setVersion_Base> Callback_PlateAcquisitionAnnotationLink_setVersionPtr;

class Callback_PlateAcquisitionAnnotationLink_getParent_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_PlateAcquisitionAnnotationLink_getParent_Base> Callback_PlateAcquisitionAnnotationLink_getParentPtr;

class Callback_PlateAcquisitionAnnotationLink_setParent_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_PlateAcquisitionAnnotationLink_setParent_Base> Callback_PlateAcquisitionAnnotationLink_setParentPtr;

class Callback_PlateAcquisitionAnnotationLink_getChild_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_PlateAcquisitionAnnotationLink_getChild_Base> Callback_PlateAcquisitionAnnotationLink_getChildPtr;

class Callback_PlateAcquisitionAnnotationLink_setChild_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_PlateAcquisitionAnnotationLink_setChild_Base> Callback_PlateAcquisitionAnnotationLink_setChildPtr;

class Callback_PlateAcquisitionAnnotationLink_link_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_PlateAcquisitionAnnotationLink_link_Base> Callback_PlateAcquisitionAnnotationLink_linkPtr;

}

}

namespace IceProxy
{

namespace omero
{

namespace model
{

class PlateAcquisitionAnnotationLink : virtual public ::IceProxy::omero::model::IObject
{
public:

    ::omero::RIntPtr getVersion()
    {
        return getVersion(0);
    }
    ::omero::RIntPtr getVersion(const ::Ice::Context& __ctx)
    {
        return getVersion(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_getVersion()
    {
        return begin_getVersion(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::Context& __ctx)
    {
        return begin_getVersion(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getVersion(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getVersion(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::omero::model::Callback_PlateAcquisitionAnnotationLink_getVersionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getVersion(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::Context& __ctx, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_getVersionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getVersion(&__ctx, __del, __cookie);
    }

    ::omero::RIntPtr end_getVersion(const ::Ice::AsyncResultPtr&);
    
private:

    ::omero::RIntPtr getVersion(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setVersion(const ::omero::RIntPtr& theVersion)
    {
        setVersion(theVersion, 0);
    }
    void setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::Context& __ctx)
    {
        setVersion(theVersion, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion)
    {
        return begin_setVersion(theVersion, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::Context& __ctx)
    {
        return begin_setVersion(theVersion, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setVersion(theVersion, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setVersion(theVersion, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_setVersionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setVersion(theVersion, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::Context& __ctx, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_setVersionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setVersion(theVersion, &__ctx, __del, __cookie);
    }

    void end_setVersion(const ::Ice::AsyncResultPtr&);
    
private:

    void setVersion(const ::omero::RIntPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::omero::model::PlateAcquisitionPtr getParent()
    {
        return getParent(0);
    }
    ::omero::model::PlateAcquisitionPtr getParent(const ::Ice::Context& __ctx)
    {
        return getParent(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_getParent()
    {
        return begin_getParent(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getParent(const ::Ice::Context& __ctx)
    {
        return begin_getParent(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getParent(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getParent(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getParent(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getParent(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getParent(const ::omero::model::Callback_PlateAcquisitionAnnotationLink_getParentPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getParent(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getParent(const ::Ice::Context& __ctx, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_getParentPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getParent(&__ctx, __del, __cookie);
    }

    ::omero::model::PlateAcquisitionPtr end_getParent(const ::Ice::AsyncResultPtr&);
    
private:

    ::omero::model::PlateAcquisitionPtr getParent(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getParent(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setParent(const ::omero::model::PlateAcquisitionPtr& theParent)
    {
        setParent(theParent, 0);
    }
    void setParent(const ::omero::model::PlateAcquisitionPtr& theParent, const ::Ice::Context& __ctx)
    {
        setParent(theParent, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setParent(const ::omero::model::PlateAcquisitionPtr& theParent)
    {
        return begin_setParent(theParent, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setParent(const ::omero::model::PlateAcquisitionPtr& theParent, const ::Ice::Context& __ctx)
    {
        return begin_setParent(theParent, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setParent(const ::omero::model::PlateAcquisitionPtr& theParent, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setParent(theParent, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setParent(const ::omero::model::PlateAcquisitionPtr& theParent, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setParent(theParent, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setParent(const ::omero::model::PlateAcquisitionPtr& theParent, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_setParentPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setParent(theParent, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setParent(const ::omero::model::PlateAcquisitionPtr& theParent, const ::Ice::Context& __ctx, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_setParentPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setParent(theParent, &__ctx, __del, __cookie);
    }

    void end_setParent(const ::Ice::AsyncResultPtr&);
    
private:

    void setParent(const ::omero::model::PlateAcquisitionPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setParent(const ::omero::model::PlateAcquisitionPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::omero::model::AnnotationPtr getChild()
    {
        return getChild(0);
    }
    ::omero::model::AnnotationPtr getChild(const ::Ice::Context& __ctx)
    {
        return getChild(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_getChild()
    {
        return begin_getChild(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getChild(const ::Ice::Context& __ctx)
    {
        return begin_getChild(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getChild(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getChild(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getChild(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getChild(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getChild(const ::omero::model::Callback_PlateAcquisitionAnnotationLink_getChildPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getChild(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getChild(const ::Ice::Context& __ctx, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_getChildPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getChild(&__ctx, __del, __cookie);
    }

    ::omero::model::AnnotationPtr end_getChild(const ::Ice::AsyncResultPtr&);
    
private:

    ::omero::model::AnnotationPtr getChild(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getChild(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setChild(const ::omero::model::AnnotationPtr& theChild)
    {
        setChild(theChild, 0);
    }
    void setChild(const ::omero::model::AnnotationPtr& theChild, const ::Ice::Context& __ctx)
    {
        setChild(theChild, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setChild(const ::omero::model::AnnotationPtr& theChild)
    {
        return begin_setChild(theChild, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setChild(const ::omero::model::AnnotationPtr& theChild, const ::Ice::Context& __ctx)
    {
        return begin_setChild(theChild, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setChild(const ::omero::model::AnnotationPtr& theChild, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setChild(theChild, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setChild(const ::omero::model::AnnotationPtr& theChild, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setChild(theChild, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setChild(const ::omero::model::AnnotationPtr& theChild, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_setChildPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setChild(theChild, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setChild(const ::omero::model::AnnotationPtr& theChild, const ::Ice::Context& __ctx, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_setChildPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setChild(theChild, &__ctx, __del, __cookie);
    }

    void end_setChild(const ::Ice::AsyncResultPtr&);
    
private:

    void setChild(const ::omero::model::AnnotationPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setChild(const ::omero::model::AnnotationPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void link(const ::omero::model::PlateAcquisitionPtr& theParent, const ::omero::model::AnnotationPtr& theChild)
    {
        link(theParent, theChild, 0);
    }
    void link(const ::omero::model::PlateAcquisitionPtr& theParent, const ::omero::model::AnnotationPtr& theChild, const ::Ice::Context& __ctx)
    {
        link(theParent, theChild, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_link(const ::omero::model::PlateAcquisitionPtr& theParent, const ::omero::model::AnnotationPtr& theChild)
    {
        return begin_link(theParent, theChild, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_link(const ::omero::model::PlateAcquisitionPtr& theParent, const ::omero::model::AnnotationPtr& theChild, const ::Ice::Context& __ctx)
    {
        return begin_link(theParent, theChild, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_link(const ::omero::model::PlateAcquisitionPtr& theParent, const ::omero::model::AnnotationPtr& theChild, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_link(theParent, theChild, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_link(const ::omero::model::PlateAcquisitionPtr& theParent, const ::omero::model::AnnotationPtr& theChild, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_link(theParent, theChild, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_link(const ::omero::model::PlateAcquisitionPtr& theParent, const ::omero::model::AnnotationPtr& theChild, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_linkPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_link(theParent, theChild, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_link(const ::omero::model::PlateAcquisitionPtr& theParent, const ::omero::model::AnnotationPtr& theChild, const ::Ice::Context& __ctx, const ::omero::model::Callback_PlateAcquisitionAnnotationLink_linkPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_link(theParent, theChild, &__ctx, __del, __cookie);
    }

    void end_link(const ::Ice::AsyncResultPtr&);
    
private:

    void link(const ::omero::model::PlateAcquisitionPtr&, const ::omero::model::AnnotationPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_link(const ::omero::model::PlateAcquisitionPtr&, const ::omero::model::AnnotationPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<PlateAcquisitionAnnotationLink> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<PlateAcquisitionAnnotationLink*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

}

namespace IceDelegate
{

namespace omero
{

namespace model
{

class PlateAcquisitionAnnotationLink : virtual public ::IceDelegate::omero::model::IObject
{
public:

    virtual ::omero::RIntPtr getVersion(const ::Ice::Context*) = 0;

    virtual void setVersion(const ::omero::RIntPtr&, const ::Ice::Context*) = 0;

    virtual ::omero::model::PlateAcquisitionPtr getParent(const ::Ice::Context*) = 0;

    virtual void setParent(const ::omero::model::PlateAcquisitionPtr&, const ::Ice::Context*) = 0;

    virtual ::omero::model::AnnotationPtr getChild(const ::Ice::Context*) = 0;

    virtual void setChild(const ::omero::model::AnnotationPtr&, const ::Ice::Context*) = 0;

    virtual void link(const ::omero::model::PlateAcquisitionPtr&, const ::omero::model::AnnotationPtr&, const ::Ice::Context*) = 0;
};

}

}

}

namespace IceDelegateM
{

namespace omero
{

namespace model
{

class PlateAcquisitionAnnotationLink : virtual public ::IceDelegate::omero::model::PlateAcquisitionAnnotationLink,
                                       virtual public ::IceDelegateM::omero::model::IObject
{
public:

    virtual ::omero::RIntPtr getVersion(const ::Ice::Context*);

    virtual void setVersion(const ::omero::RIntPtr&, const ::Ice::Context*);

    virtual ::omero::model::PlateAcquisitionPtr getParent(const ::Ice::Context*);

    virtual void setParent(const ::omero::model::PlateAcquisitionPtr&, const ::Ice::Context*);

    virtual ::omero::model::AnnotationPtr getChild(const ::Ice::Context*);

    virtual void setChild(const ::omero::model::AnnotationPtr&, const ::Ice::Context*);

    virtual void link(const ::omero::model::PlateAcquisitionPtr&, const ::omero::model::AnnotationPtr&, const ::Ice::Context*);
};

}

}

}

namespace IceDelegateD
{

namespace omero
{

namespace model
{

class PlateAcquisitionAnnotationLink : virtual public ::IceDelegate::omero::model::PlateAcquisitionAnnotationLink,
                                       virtual public ::IceDelegateD::omero::model::IObject
{
public:

    virtual ::omero::RIntPtr getVersion(const ::Ice::Context*);

    virtual void setVersion(const ::omero::RIntPtr&, const ::Ice::Context*);

    virtual ::omero::model::PlateAcquisitionPtr getParent(const ::Ice::Context*);

    virtual void setParent(const ::omero::model::PlateAcquisitionPtr&, const ::Ice::Context*);

    virtual ::omero::model::AnnotationPtr getChild(const ::Ice::Context*);

    virtual void setChild(const ::omero::model::AnnotationPtr&, const ::Ice::Context*);

    virtual void link(const ::omero::model::PlateAcquisitionPtr&, const ::omero::model::AnnotationPtr&, const ::Ice::Context*);
};

}

}

}

namespace omero
{

namespace model
{

class PlateAcquisitionAnnotationLink : public ::omero::model::IObject
{
public:

    typedef PlateAcquisitionAnnotationLinkPrx ProxyType;
    typedef PlateAcquisitionAnnotationLinkPtr PointerType;
    
    PlateAcquisitionAnnotationLink() {}
    PlateAcquisitionAnnotationLink(const ::omero::RLongPtr&, const ::omero::model::DetailsPtr&, bool, const ::omero::RIntPtr&, const ::omero::model::PlateAcquisitionPtr&, const ::omero::model::AnnotationPtr&);
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void __gcReachable(::IceInternal::GCCountMap&) const;
    virtual void __gcClear();

    virtual ::omero::RIntPtr getVersion(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getVersion(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setVersion(const ::omero::RIntPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setVersion(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::omero::model::PlateAcquisitionPtr getParent(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getParent(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setParent(const ::omero::model::PlateAcquisitionPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setParent(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::omero::model::AnnotationPtr getChild(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getChild(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setChild(const ::omero::model::AnnotationPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setChild(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void link(const ::omero::model::PlateAcquisitionPtr&, const ::omero::model::AnnotationPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___link(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif

protected:

    ::omero::RIntPtr version;

    ::omero::model::PlateAcquisitionPtr parent;

    ::omero::model::AnnotationPtr child;
};

inline bool operator==(const PlateAcquisitionAnnotationLink& l, const PlateAcquisitionAnnotationLink& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const PlateAcquisitionAnnotationLink& l, const PlateAcquisitionAnnotationLink& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

}

namespace omero
{

namespace model
{

template<class T>
class CallbackNC_PlateAcquisitionAnnotationLink_getVersion : public Callback_PlateAcquisitionAnnotationLink_getVersion_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::omero::RIntPtr&);

    CallbackNC_PlateAcquisitionAnnotationLink_getVersion(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::PlateAcquisitionAnnotationLinkPrx __proxy = ::omero::model::PlateAcquisitionAnnotationLinkPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getVersion(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_PlateAcquisitionAnnotationLink_getVersionPtr
newCallback_PlateAcquisitionAnnotationLink_getVersion(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_getVersion<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_getVersionPtr
newCallback_PlateAcquisitionAnnotationLink_getVersion(T* instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_getVersion<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_PlateAcquisitionAnnotationLink_getVersion : public Callback_PlateAcquisitionAnnotationLink_getVersion_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::omero::RIntPtr&, const CT&);

    Callback_PlateAcquisitionAnnotationLink_getVersion(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::PlateAcquisitionAnnotationLinkPrx __proxy = ::omero::model::PlateAcquisitionAnnotationLinkPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getVersion(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_getVersionPtr
newCallback_PlateAcquisitionAnnotationLink_getVersion(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_getVersion<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_getVersionPtr
newCallback_PlateAcquisitionAnnotationLink_getVersion(T* instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_getVersion<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_PlateAcquisitionAnnotationLink_setVersion : public Callback_PlateAcquisitionAnnotationLink_setVersion_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_PlateAcquisitionAnnotationLink_setVersion(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_PlateAcquisitionAnnotationLink_setVersionPtr
newCallback_PlateAcquisitionAnnotationLink_setVersion(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setVersion<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_setVersionPtr
newCallback_PlateAcquisitionAnnotationLink_setVersion(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setVersion<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_setVersionPtr
newCallback_PlateAcquisitionAnnotationLink_setVersion(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setVersion<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_setVersionPtr
newCallback_PlateAcquisitionAnnotationLink_setVersion(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setVersion<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_PlateAcquisitionAnnotationLink_setVersion : public Callback_PlateAcquisitionAnnotationLink_setVersion_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_PlateAcquisitionAnnotationLink_setVersion(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setVersionPtr
newCallback_PlateAcquisitionAnnotationLink_setVersion(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setVersion<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setVersionPtr
newCallback_PlateAcquisitionAnnotationLink_setVersion(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setVersion<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setVersionPtr
newCallback_PlateAcquisitionAnnotationLink_setVersion(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setVersion<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setVersionPtr
newCallback_PlateAcquisitionAnnotationLink_setVersion(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setVersion<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_PlateAcquisitionAnnotationLink_getParent : public Callback_PlateAcquisitionAnnotationLink_getParent_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::omero::model::PlateAcquisitionPtr&);

    CallbackNC_PlateAcquisitionAnnotationLink_getParent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::PlateAcquisitionAnnotationLinkPrx __proxy = ::omero::model::PlateAcquisitionAnnotationLinkPrx::uncheckedCast(__result->getProxy());
        ::omero::model::PlateAcquisitionPtr __ret;
        try
        {
            __ret = __proxy->end_getParent(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_PlateAcquisitionAnnotationLink_getParentPtr
newCallback_PlateAcquisitionAnnotationLink_getParent(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::model::PlateAcquisitionPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_getParent<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_getParentPtr
newCallback_PlateAcquisitionAnnotationLink_getParent(T* instance, void (T::*cb)(const ::omero::model::PlateAcquisitionPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_getParent<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_PlateAcquisitionAnnotationLink_getParent : public Callback_PlateAcquisitionAnnotationLink_getParent_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::omero::model::PlateAcquisitionPtr&, const CT&);

    Callback_PlateAcquisitionAnnotationLink_getParent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::PlateAcquisitionAnnotationLinkPrx __proxy = ::omero::model::PlateAcquisitionAnnotationLinkPrx::uncheckedCast(__result->getProxy());
        ::omero::model::PlateAcquisitionPtr __ret;
        try
        {
            __ret = __proxy->end_getParent(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_getParentPtr
newCallback_PlateAcquisitionAnnotationLink_getParent(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::model::PlateAcquisitionPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_getParent<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_getParentPtr
newCallback_PlateAcquisitionAnnotationLink_getParent(T* instance, void (T::*cb)(const ::omero::model::PlateAcquisitionPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_getParent<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_PlateAcquisitionAnnotationLink_setParent : public Callback_PlateAcquisitionAnnotationLink_setParent_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_PlateAcquisitionAnnotationLink_setParent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_PlateAcquisitionAnnotationLink_setParentPtr
newCallback_PlateAcquisitionAnnotationLink_setParent(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setParent<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_setParentPtr
newCallback_PlateAcquisitionAnnotationLink_setParent(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setParent<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_setParentPtr
newCallback_PlateAcquisitionAnnotationLink_setParent(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setParent<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_setParentPtr
newCallback_PlateAcquisitionAnnotationLink_setParent(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setParent<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_PlateAcquisitionAnnotationLink_setParent : public Callback_PlateAcquisitionAnnotationLink_setParent_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_PlateAcquisitionAnnotationLink_setParent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setParentPtr
newCallback_PlateAcquisitionAnnotationLink_setParent(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setParent<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setParentPtr
newCallback_PlateAcquisitionAnnotationLink_setParent(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setParent<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setParentPtr
newCallback_PlateAcquisitionAnnotationLink_setParent(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setParent<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setParentPtr
newCallback_PlateAcquisitionAnnotationLink_setParent(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setParent<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_PlateAcquisitionAnnotationLink_getChild : public Callback_PlateAcquisitionAnnotationLink_getChild_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::omero::model::AnnotationPtr&);

    CallbackNC_PlateAcquisitionAnnotationLink_getChild(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::PlateAcquisitionAnnotationLinkPrx __proxy = ::omero::model::PlateAcquisitionAnnotationLinkPrx::uncheckedCast(__result->getProxy());
        ::omero::model::AnnotationPtr __ret;
        try
        {
            __ret = __proxy->end_getChild(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_PlateAcquisitionAnnotationLink_getChildPtr
newCallback_PlateAcquisitionAnnotationLink_getChild(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::model::AnnotationPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_getChild<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_getChildPtr
newCallback_PlateAcquisitionAnnotationLink_getChild(T* instance, void (T::*cb)(const ::omero::model::AnnotationPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_getChild<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_PlateAcquisitionAnnotationLink_getChild : public Callback_PlateAcquisitionAnnotationLink_getChild_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::omero::model::AnnotationPtr&, const CT&);

    Callback_PlateAcquisitionAnnotationLink_getChild(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::PlateAcquisitionAnnotationLinkPrx __proxy = ::omero::model::PlateAcquisitionAnnotationLinkPrx::uncheckedCast(__result->getProxy());
        ::omero::model::AnnotationPtr __ret;
        try
        {
            __ret = __proxy->end_getChild(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_getChildPtr
newCallback_PlateAcquisitionAnnotationLink_getChild(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::model::AnnotationPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_getChild<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_getChildPtr
newCallback_PlateAcquisitionAnnotationLink_getChild(T* instance, void (T::*cb)(const ::omero::model::AnnotationPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_getChild<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_PlateAcquisitionAnnotationLink_setChild : public Callback_PlateAcquisitionAnnotationLink_setChild_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_PlateAcquisitionAnnotationLink_setChild(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_PlateAcquisitionAnnotationLink_setChildPtr
newCallback_PlateAcquisitionAnnotationLink_setChild(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setChild<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_setChildPtr
newCallback_PlateAcquisitionAnnotationLink_setChild(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setChild<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_setChildPtr
newCallback_PlateAcquisitionAnnotationLink_setChild(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setChild<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_setChildPtr
newCallback_PlateAcquisitionAnnotationLink_setChild(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_setChild<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_PlateAcquisitionAnnotationLink_setChild : public Callback_PlateAcquisitionAnnotationLink_setChild_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_PlateAcquisitionAnnotationLink_setChild(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setChildPtr
newCallback_PlateAcquisitionAnnotationLink_setChild(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setChild<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setChildPtr
newCallback_PlateAcquisitionAnnotationLink_setChild(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setChild<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setChildPtr
newCallback_PlateAcquisitionAnnotationLink_setChild(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setChild<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_setChildPtr
newCallback_PlateAcquisitionAnnotationLink_setChild(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_setChild<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_PlateAcquisitionAnnotationLink_link : public Callback_PlateAcquisitionAnnotationLink_link_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_PlateAcquisitionAnnotationLink_link(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_PlateAcquisitionAnnotationLink_linkPtr
newCallback_PlateAcquisitionAnnotationLink_link(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_link<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_linkPtr
newCallback_PlateAcquisitionAnnotationLink_link(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_link<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_linkPtr
newCallback_PlateAcquisitionAnnotationLink_link(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_link<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PlateAcquisitionAnnotationLink_linkPtr
newCallback_PlateAcquisitionAnnotationLink_link(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PlateAcquisitionAnnotationLink_link<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_PlateAcquisitionAnnotationLink_link : public Callback_PlateAcquisitionAnnotationLink_link_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_PlateAcquisitionAnnotationLink_link(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_linkPtr
newCallback_PlateAcquisitionAnnotationLink_link(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_link<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_linkPtr
newCallback_PlateAcquisitionAnnotationLink_link(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_link<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_linkPtr
newCallback_PlateAcquisitionAnnotationLink_link(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_link<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PlateAcquisitionAnnotationLink_linkPtr
newCallback_PlateAcquisitionAnnotationLink_link(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PlateAcquisitionAnnotationLink_link<T, CT>(instance, 0, excb, sentcb);
}

}

}

#endif
