// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `QuantumDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __omero_model__opt_hudson_workspace_OMERO_5_0_release_src_components_blitz_generated_omero_model_QuantumDef_h__
#define __omero_model__opt_hudson_workspace_OMERO_5_0_release_src_components_blitz_generated_omero_model_QuantumDef_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <omero/model/IObject.h>
#include <omero/RTypes.h>
#include <omero/System.h>
#include <omero/Collections.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace omero
{

namespace model
{

class Details;

class QuantumDef;

}

}

}

namespace omero
{

namespace model
{

class Details;
bool operator==(const Details&, const Details&);
bool operator<(const Details&, const Details&);

class QuantumDef;
bool operator==(const QuantumDef&, const QuantumDef&);
bool operator<(const QuantumDef&, const QuantumDef&);

}

}

namespace IceInternal
{

::Ice::Object* upCast(::omero::model::Details*);
::IceProxy::Ice::Object* upCast(::IceProxy::omero::model::Details*);

::Ice::Object* upCast(::omero::model::QuantumDef*);
::IceProxy::Ice::Object* upCast(::IceProxy::omero::model::QuantumDef*);

}

namespace omero
{

namespace model
{

typedef ::IceInternal::Handle< ::omero::model::Details> DetailsPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::omero::model::Details> DetailsPrx;

void __read(::IceInternal::BasicStream*, DetailsPrx&);
void __patch__DetailsPtr(void*, ::Ice::ObjectPtr&);

typedef ::IceInternal::Handle< ::omero::model::QuantumDef> QuantumDefPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::omero::model::QuantumDef> QuantumDefPrx;

void __read(::IceInternal::BasicStream*, QuantumDefPrx&);
void __patch__QuantumDefPtr(void*, ::Ice::ObjectPtr&);

}

}

namespace omero
{

namespace model
{

class Callback_QuantumDef_getVersion_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QuantumDef_getVersion_Base> Callback_QuantumDef_getVersionPtr;

class Callback_QuantumDef_setVersion_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QuantumDef_setVersion_Base> Callback_QuantumDef_setVersionPtr;

class Callback_QuantumDef_getCdStart_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QuantumDef_getCdStart_Base> Callback_QuantumDef_getCdStartPtr;

class Callback_QuantumDef_setCdStart_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QuantumDef_setCdStart_Base> Callback_QuantumDef_setCdStartPtr;

class Callback_QuantumDef_getCdEnd_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QuantumDef_getCdEnd_Base> Callback_QuantumDef_getCdEndPtr;

class Callback_QuantumDef_setCdEnd_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QuantumDef_setCdEnd_Base> Callback_QuantumDef_setCdEndPtr;

class Callback_QuantumDef_getBitResolution_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QuantumDef_getBitResolution_Base> Callback_QuantumDef_getBitResolutionPtr;

class Callback_QuantumDef_setBitResolution_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QuantumDef_setBitResolution_Base> Callback_QuantumDef_setBitResolutionPtr;

}

}

namespace IceProxy
{

namespace omero
{

namespace model
{

class QuantumDef : virtual public ::IceProxy::omero::model::IObject
{
public:

    ::omero::RIntPtr getVersion()
    {
        return getVersion(0);
    }
    ::omero::RIntPtr getVersion(const ::Ice::Context& __ctx)
    {
        return getVersion(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_getVersion()
    {
        return begin_getVersion(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::Context& __ctx)
    {
        return begin_getVersion(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getVersion(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getVersion(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::omero::model::Callback_QuantumDef_getVersionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getVersion(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::Context& __ctx, const ::omero::model::Callback_QuantumDef_getVersionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getVersion(&__ctx, __del, __cookie);
    }

    ::omero::RIntPtr end_getVersion(const ::Ice::AsyncResultPtr&);
    
private:

    ::omero::RIntPtr getVersion(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getVersion(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setVersion(const ::omero::RIntPtr& theVersion)
    {
        setVersion(theVersion, 0);
    }
    void setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::Context& __ctx)
    {
        setVersion(theVersion, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion)
    {
        return begin_setVersion(theVersion, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::Context& __ctx)
    {
        return begin_setVersion(theVersion, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setVersion(theVersion, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setVersion(theVersion, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::omero::model::Callback_QuantumDef_setVersionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setVersion(theVersion, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr& theVersion, const ::Ice::Context& __ctx, const ::omero::model::Callback_QuantumDef_setVersionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setVersion(theVersion, &__ctx, __del, __cookie);
    }

    void end_setVersion(const ::Ice::AsyncResultPtr&);
    
private:

    void setVersion(const ::omero::RIntPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setVersion(const ::omero::RIntPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::omero::RIntPtr getCdStart()
    {
        return getCdStart(0);
    }
    ::omero::RIntPtr getCdStart(const ::Ice::Context& __ctx)
    {
        return getCdStart(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_getCdStart()
    {
        return begin_getCdStart(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getCdStart(const ::Ice::Context& __ctx)
    {
        return begin_getCdStart(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getCdStart(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getCdStart(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getCdStart(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getCdStart(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getCdStart(const ::omero::model::Callback_QuantumDef_getCdStartPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getCdStart(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getCdStart(const ::Ice::Context& __ctx, const ::omero::model::Callback_QuantumDef_getCdStartPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getCdStart(&__ctx, __del, __cookie);
    }

    ::omero::RIntPtr end_getCdStart(const ::Ice::AsyncResultPtr&);
    
private:

    ::omero::RIntPtr getCdStart(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getCdStart(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setCdStart(const ::omero::RIntPtr& theCdStart)
    {
        setCdStart(theCdStart, 0);
    }
    void setCdStart(const ::omero::RIntPtr& theCdStart, const ::Ice::Context& __ctx)
    {
        setCdStart(theCdStart, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setCdStart(const ::omero::RIntPtr& theCdStart)
    {
        return begin_setCdStart(theCdStart, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setCdStart(const ::omero::RIntPtr& theCdStart, const ::Ice::Context& __ctx)
    {
        return begin_setCdStart(theCdStart, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setCdStart(const ::omero::RIntPtr& theCdStart, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setCdStart(theCdStart, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setCdStart(const ::omero::RIntPtr& theCdStart, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setCdStart(theCdStart, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setCdStart(const ::omero::RIntPtr& theCdStart, const ::omero::model::Callback_QuantumDef_setCdStartPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setCdStart(theCdStart, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setCdStart(const ::omero::RIntPtr& theCdStart, const ::Ice::Context& __ctx, const ::omero::model::Callback_QuantumDef_setCdStartPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setCdStart(theCdStart, &__ctx, __del, __cookie);
    }

    void end_setCdStart(const ::Ice::AsyncResultPtr&);
    
private:

    void setCdStart(const ::omero::RIntPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setCdStart(const ::omero::RIntPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::omero::RIntPtr getCdEnd()
    {
        return getCdEnd(0);
    }
    ::omero::RIntPtr getCdEnd(const ::Ice::Context& __ctx)
    {
        return getCdEnd(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_getCdEnd()
    {
        return begin_getCdEnd(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getCdEnd(const ::Ice::Context& __ctx)
    {
        return begin_getCdEnd(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getCdEnd(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getCdEnd(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getCdEnd(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getCdEnd(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getCdEnd(const ::omero::model::Callback_QuantumDef_getCdEndPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getCdEnd(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getCdEnd(const ::Ice::Context& __ctx, const ::omero::model::Callback_QuantumDef_getCdEndPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getCdEnd(&__ctx, __del, __cookie);
    }

    ::omero::RIntPtr end_getCdEnd(const ::Ice::AsyncResultPtr&);
    
private:

    ::omero::RIntPtr getCdEnd(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getCdEnd(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setCdEnd(const ::omero::RIntPtr& theCdEnd)
    {
        setCdEnd(theCdEnd, 0);
    }
    void setCdEnd(const ::omero::RIntPtr& theCdEnd, const ::Ice::Context& __ctx)
    {
        setCdEnd(theCdEnd, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setCdEnd(const ::omero::RIntPtr& theCdEnd)
    {
        return begin_setCdEnd(theCdEnd, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setCdEnd(const ::omero::RIntPtr& theCdEnd, const ::Ice::Context& __ctx)
    {
        return begin_setCdEnd(theCdEnd, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setCdEnd(const ::omero::RIntPtr& theCdEnd, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setCdEnd(theCdEnd, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setCdEnd(const ::omero::RIntPtr& theCdEnd, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setCdEnd(theCdEnd, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setCdEnd(const ::omero::RIntPtr& theCdEnd, const ::omero::model::Callback_QuantumDef_setCdEndPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setCdEnd(theCdEnd, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setCdEnd(const ::omero::RIntPtr& theCdEnd, const ::Ice::Context& __ctx, const ::omero::model::Callback_QuantumDef_setCdEndPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setCdEnd(theCdEnd, &__ctx, __del, __cookie);
    }

    void end_setCdEnd(const ::Ice::AsyncResultPtr&);
    
private:

    void setCdEnd(const ::omero::RIntPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setCdEnd(const ::omero::RIntPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::omero::RIntPtr getBitResolution()
    {
        return getBitResolution(0);
    }
    ::omero::RIntPtr getBitResolution(const ::Ice::Context& __ctx)
    {
        return getBitResolution(&__ctx);
    }

    ::Ice::AsyncResultPtr begin_getBitResolution()
    {
        return begin_getBitResolution(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getBitResolution(const ::Ice::Context& __ctx)
    {
        return begin_getBitResolution(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getBitResolution(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getBitResolution(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getBitResolution(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getBitResolution(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getBitResolution(const ::omero::model::Callback_QuantumDef_getBitResolutionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getBitResolution(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getBitResolution(const ::Ice::Context& __ctx, const ::omero::model::Callback_QuantumDef_getBitResolutionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getBitResolution(&__ctx, __del, __cookie);
    }

    ::omero::RIntPtr end_getBitResolution(const ::Ice::AsyncResultPtr&);
    
private:

    ::omero::RIntPtr getBitResolution(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getBitResolution(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setBitResolution(const ::omero::RIntPtr& theBitResolution)
    {
        setBitResolution(theBitResolution, 0);
    }
    void setBitResolution(const ::omero::RIntPtr& theBitResolution, const ::Ice::Context& __ctx)
    {
        setBitResolution(theBitResolution, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setBitResolution(const ::omero::RIntPtr& theBitResolution)
    {
        return begin_setBitResolution(theBitResolution, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setBitResolution(const ::omero::RIntPtr& theBitResolution, const ::Ice::Context& __ctx)
    {
        return begin_setBitResolution(theBitResolution, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setBitResolution(const ::omero::RIntPtr& theBitResolution, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setBitResolution(theBitResolution, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setBitResolution(const ::omero::RIntPtr& theBitResolution, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setBitResolution(theBitResolution, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setBitResolution(const ::omero::RIntPtr& theBitResolution, const ::omero::model::Callback_QuantumDef_setBitResolutionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setBitResolution(theBitResolution, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setBitResolution(const ::omero::RIntPtr& theBitResolution, const ::Ice::Context& __ctx, const ::omero::model::Callback_QuantumDef_setBitResolutionPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setBitResolution(theBitResolution, &__ctx, __del, __cookie);
    }

    void end_setBitResolution(const ::Ice::AsyncResultPtr&);
    
private:

    void setBitResolution(const ::omero::RIntPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setBitResolution(const ::omero::RIntPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<QuantumDef> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<QuantumDef*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<QuantumDef*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

}

namespace IceDelegate
{

namespace omero
{

namespace model
{

class QuantumDef : virtual public ::IceDelegate::omero::model::IObject
{
public:

    virtual ::omero::RIntPtr getVersion(const ::Ice::Context*) = 0;

    virtual void setVersion(const ::omero::RIntPtr&, const ::Ice::Context*) = 0;

    virtual ::omero::RIntPtr getCdStart(const ::Ice::Context*) = 0;

    virtual void setCdStart(const ::omero::RIntPtr&, const ::Ice::Context*) = 0;

    virtual ::omero::RIntPtr getCdEnd(const ::Ice::Context*) = 0;

    virtual void setCdEnd(const ::omero::RIntPtr&, const ::Ice::Context*) = 0;

    virtual ::omero::RIntPtr getBitResolution(const ::Ice::Context*) = 0;

    virtual void setBitResolution(const ::omero::RIntPtr&, const ::Ice::Context*) = 0;
};

}

}

}

namespace IceDelegateM
{

namespace omero
{

namespace model
{

class QuantumDef : virtual public ::IceDelegate::omero::model::QuantumDef,
                   virtual public ::IceDelegateM::omero::model::IObject
{
public:

    virtual ::omero::RIntPtr getVersion(const ::Ice::Context*);

    virtual void setVersion(const ::omero::RIntPtr&, const ::Ice::Context*);

    virtual ::omero::RIntPtr getCdStart(const ::Ice::Context*);

    virtual void setCdStart(const ::omero::RIntPtr&, const ::Ice::Context*);

    virtual ::omero::RIntPtr getCdEnd(const ::Ice::Context*);

    virtual void setCdEnd(const ::omero::RIntPtr&, const ::Ice::Context*);

    virtual ::omero::RIntPtr getBitResolution(const ::Ice::Context*);

    virtual void setBitResolution(const ::omero::RIntPtr&, const ::Ice::Context*);
};

}

}

}

namespace IceDelegateD
{

namespace omero
{

namespace model
{

class QuantumDef : virtual public ::IceDelegate::omero::model::QuantumDef,
                   virtual public ::IceDelegateD::omero::model::IObject
{
public:

    virtual ::omero::RIntPtr getVersion(const ::Ice::Context*);

    virtual void setVersion(const ::omero::RIntPtr&, const ::Ice::Context*);

    virtual ::omero::RIntPtr getCdStart(const ::Ice::Context*);

    virtual void setCdStart(const ::omero::RIntPtr&, const ::Ice::Context*);

    virtual ::omero::RIntPtr getCdEnd(const ::Ice::Context*);

    virtual void setCdEnd(const ::omero::RIntPtr&, const ::Ice::Context*);

    virtual ::omero::RIntPtr getBitResolution(const ::Ice::Context*);

    virtual void setBitResolution(const ::omero::RIntPtr&, const ::Ice::Context*);
};

}

}

}

namespace omero
{

namespace model
{

class QuantumDef : public ::omero::model::IObject
{
public:

    typedef QuantumDefPrx ProxyType;
    typedef QuantumDefPtr PointerType;
    
    QuantumDef() {}
    QuantumDef(const ::omero::RLongPtr&, const ::omero::model::DetailsPtr&, bool, const ::omero::RIntPtr&, const ::omero::RIntPtr&, const ::omero::RIntPtr&, const ::omero::RIntPtr&);
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void __gcReachable(::IceInternal::GCCountMap&) const;
    virtual void __gcClear();

    virtual ::omero::RIntPtr getVersion(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getVersion(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setVersion(const ::omero::RIntPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setVersion(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::omero::RIntPtr getCdStart(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getCdStart(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setCdStart(const ::omero::RIntPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setCdStart(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::omero::RIntPtr getCdEnd(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getCdEnd(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setCdEnd(const ::omero::RIntPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setCdEnd(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::omero::RIntPtr getBitResolution(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getBitResolution(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setBitResolution(const ::omero::RIntPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setBitResolution(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif

protected:

    ::omero::RIntPtr version;

    ::omero::RIntPtr cdStart;

    ::omero::RIntPtr cdEnd;

    ::omero::RIntPtr bitResolution;
};

inline bool operator==(const QuantumDef& l, const QuantumDef& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const QuantumDef& l, const QuantumDef& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

}

namespace omero
{

namespace model
{

template<class T>
class CallbackNC_QuantumDef_getVersion : public Callback_QuantumDef_getVersion_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::omero::RIntPtr&);

    CallbackNC_QuantumDef_getVersion(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::QuantumDefPrx __proxy = ::omero::model::QuantumDefPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getVersion(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_QuantumDef_getVersionPtr
newCallback_QuantumDef_getVersion(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_getVersion<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_getVersionPtr
newCallback_QuantumDef_getVersion(T* instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_getVersion<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_QuantumDef_getVersion : public Callback_QuantumDef_getVersion_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::omero::RIntPtr&, const CT&);

    Callback_QuantumDef_getVersion(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::QuantumDefPrx __proxy = ::omero::model::QuantumDefPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getVersion(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_QuantumDef_getVersionPtr
newCallback_QuantumDef_getVersion(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_getVersion<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_getVersionPtr
newCallback_QuantumDef_getVersion(T* instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_getVersion<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_QuantumDef_setVersion : public Callback_QuantumDef_setVersion_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_QuantumDef_setVersion(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_QuantumDef_setVersionPtr
newCallback_QuantumDef_setVersion(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setVersion<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_setVersionPtr
newCallback_QuantumDef_setVersion(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setVersion<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_QuantumDef_setVersionPtr
newCallback_QuantumDef_setVersion(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setVersion<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_setVersionPtr
newCallback_QuantumDef_setVersion(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setVersion<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_QuantumDef_setVersion : public Callback_QuantumDef_setVersion_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_QuantumDef_setVersion(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_QuantumDef_setVersionPtr
newCallback_QuantumDef_setVersion(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setVersion<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setVersionPtr
newCallback_QuantumDef_setVersion(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setVersion<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setVersionPtr
newCallback_QuantumDef_setVersion(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setVersion<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setVersionPtr
newCallback_QuantumDef_setVersion(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setVersion<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_QuantumDef_getCdStart : public Callback_QuantumDef_getCdStart_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::omero::RIntPtr&);

    CallbackNC_QuantumDef_getCdStart(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::QuantumDefPrx __proxy = ::omero::model::QuantumDefPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getCdStart(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_QuantumDef_getCdStartPtr
newCallback_QuantumDef_getCdStart(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_getCdStart<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_getCdStartPtr
newCallback_QuantumDef_getCdStart(T* instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_getCdStart<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_QuantumDef_getCdStart : public Callback_QuantumDef_getCdStart_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::omero::RIntPtr&, const CT&);

    Callback_QuantumDef_getCdStart(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::QuantumDefPrx __proxy = ::omero::model::QuantumDefPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getCdStart(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_QuantumDef_getCdStartPtr
newCallback_QuantumDef_getCdStart(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_getCdStart<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_getCdStartPtr
newCallback_QuantumDef_getCdStart(T* instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_getCdStart<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_QuantumDef_setCdStart : public Callback_QuantumDef_setCdStart_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_QuantumDef_setCdStart(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_QuantumDef_setCdStartPtr
newCallback_QuantumDef_setCdStart(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setCdStart<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_setCdStartPtr
newCallback_QuantumDef_setCdStart(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setCdStart<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_QuantumDef_setCdStartPtr
newCallback_QuantumDef_setCdStart(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setCdStart<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_setCdStartPtr
newCallback_QuantumDef_setCdStart(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setCdStart<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_QuantumDef_setCdStart : public Callback_QuantumDef_setCdStart_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_QuantumDef_setCdStart(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_QuantumDef_setCdStartPtr
newCallback_QuantumDef_setCdStart(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setCdStart<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setCdStartPtr
newCallback_QuantumDef_setCdStart(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setCdStart<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setCdStartPtr
newCallback_QuantumDef_setCdStart(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setCdStart<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setCdStartPtr
newCallback_QuantumDef_setCdStart(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setCdStart<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_QuantumDef_getCdEnd : public Callback_QuantumDef_getCdEnd_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::omero::RIntPtr&);

    CallbackNC_QuantumDef_getCdEnd(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::QuantumDefPrx __proxy = ::omero::model::QuantumDefPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getCdEnd(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_QuantumDef_getCdEndPtr
newCallback_QuantumDef_getCdEnd(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_getCdEnd<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_getCdEndPtr
newCallback_QuantumDef_getCdEnd(T* instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_getCdEnd<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_QuantumDef_getCdEnd : public Callback_QuantumDef_getCdEnd_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::omero::RIntPtr&, const CT&);

    Callback_QuantumDef_getCdEnd(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::QuantumDefPrx __proxy = ::omero::model::QuantumDefPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getCdEnd(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_QuantumDef_getCdEndPtr
newCallback_QuantumDef_getCdEnd(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_getCdEnd<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_getCdEndPtr
newCallback_QuantumDef_getCdEnd(T* instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_getCdEnd<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_QuantumDef_setCdEnd : public Callback_QuantumDef_setCdEnd_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_QuantumDef_setCdEnd(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_QuantumDef_setCdEndPtr
newCallback_QuantumDef_setCdEnd(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setCdEnd<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_setCdEndPtr
newCallback_QuantumDef_setCdEnd(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setCdEnd<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_QuantumDef_setCdEndPtr
newCallback_QuantumDef_setCdEnd(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setCdEnd<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_setCdEndPtr
newCallback_QuantumDef_setCdEnd(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setCdEnd<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_QuantumDef_setCdEnd : public Callback_QuantumDef_setCdEnd_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_QuantumDef_setCdEnd(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_QuantumDef_setCdEndPtr
newCallback_QuantumDef_setCdEnd(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setCdEnd<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setCdEndPtr
newCallback_QuantumDef_setCdEnd(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setCdEnd<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setCdEndPtr
newCallback_QuantumDef_setCdEnd(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setCdEnd<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setCdEndPtr
newCallback_QuantumDef_setCdEnd(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setCdEnd<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_QuantumDef_getBitResolution : public Callback_QuantumDef_getBitResolution_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::omero::RIntPtr&);

    CallbackNC_QuantumDef_getBitResolution(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::QuantumDefPrx __proxy = ::omero::model::QuantumDefPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getBitResolution(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_QuantumDef_getBitResolutionPtr
newCallback_QuantumDef_getBitResolution(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_getBitResolution<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_getBitResolutionPtr
newCallback_QuantumDef_getBitResolution(T* instance, void (T::*cb)(const ::omero::RIntPtr&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_getBitResolution<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_QuantumDef_getBitResolution : public Callback_QuantumDef_getBitResolution_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::omero::RIntPtr&, const CT&);

    Callback_QuantumDef_getBitResolution(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::omero::model::QuantumDefPrx __proxy = ::omero::model::QuantumDefPrx::uncheckedCast(__result->getProxy());
        ::omero::RIntPtr __ret;
        try
        {
            __ret = __proxy->end_getBitResolution(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_QuantumDef_getBitResolutionPtr
newCallback_QuantumDef_getBitResolution(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_getBitResolution<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_getBitResolutionPtr
newCallback_QuantumDef_getBitResolution(T* instance, void (T::*cb)(const ::omero::RIntPtr&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_getBitResolution<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_QuantumDef_setBitResolution : public Callback_QuantumDef_setBitResolution_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_QuantumDef_setBitResolution(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_QuantumDef_setBitResolutionPtr
newCallback_QuantumDef_setBitResolution(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setBitResolution<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_setBitResolutionPtr
newCallback_QuantumDef_setBitResolution(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setBitResolution<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_QuantumDef_setBitResolutionPtr
newCallback_QuantumDef_setBitResolution(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setBitResolution<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QuantumDef_setBitResolutionPtr
newCallback_QuantumDef_setBitResolution(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QuantumDef_setBitResolution<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_QuantumDef_setBitResolution : public Callback_QuantumDef_setBitResolution_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_QuantumDef_setBitResolution(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_QuantumDef_setBitResolutionPtr
newCallback_QuantumDef_setBitResolution(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setBitResolution<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setBitResolutionPtr
newCallback_QuantumDef_setBitResolution(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setBitResolution<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setBitResolutionPtr
newCallback_QuantumDef_setBitResolution(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setBitResolution<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QuantumDef_setBitResolutionPtr
newCallback_QuantumDef_setBitResolution(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QuantumDef_setBitResolution<T, CT>(instance, 0, excb, sentcb);
}

}

}

#endif
